# Generated by Django 4.1.4 on 2023-01-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                ("idAdresse", models.IntegerField(primary_key=True, serialize=False)),
                ("villeAdresse", models.CharField(max_length=255)),
                ("numeroAdresse", models.CharField(max_length=42)),
                ("aliasAdresse", models.CharField(max_length=42)),
                ("rueAdresse", models.CharField(max_length=42)),
                ("CPAdresse", models.CharField(max_length=42)),
                ("paysAdresse", models.CharField(max_length=255)),
                ("autreInfoAdresse", models.CharField(max_length=255)),
                ("telAdresse", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "ADRESSE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("idClient", models.IntegerField(primary_key=True, serialize=False)),
                ("nomClient", models.CharField(max_length=255)),
                ("prenomClient", models.CharField(max_length=255)),
                ("telClient", models.CharField(max_length=255)),
                ("mailClient", models.CharField(max_length=255)),
                ("mdpClient", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "CLIENT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("idCommande", models.IntegerField(primary_key=True, serialize=False)),
                ("dateCommande", models.DateField()),
                ("promotionTotalCommande", models.FloatField()),
                ("ModeLivraison", models.CharField(max_length=42)),
                ("DateLivraison", models.DateField()),
                ("DateRetourLivraison", models.DateField()),
            ],
            options={
                "db_table": "COMMANDE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Compagnie",
            fields=[
                ("idCompagnie", models.IntegerField(primary_key=True, serialize=False)),
                ("nomCompagnie", models.CharField(max_length=255)),
                ("telCompagnie", models.CharField(max_length=255)),
                ("numSiretCompagnie", models.CharField(max_length=255)),
                ("numTVACompagnie", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "COMPAGNIE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompoCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qteProduit", models.IntegerField()),
            ],
            options={
                "db_table": "COMPOCOMMANDE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LotProduit",
            fields=[
                (
                    "idLotProduit",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("qteLotProduit", models.IntegerField()),
                ("prixUnitaireLotProduit", models.FloatField()),
            ],
            options={
                "db_table": "LOTPRODUIT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RefProduit",
            fields=[
                (
                    "idRefProduit",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nomRefProduit", models.CharField(max_length=255)),
                ("titreRefProduit", models.CharField(max_length=255)),
                ("descRefProduit", models.TextField()),
                ("datePublicationRefProduit", models.DateField()),
                ("promoRefProduit", models.FloatField()),
                ("stockRefProduit", models.IntegerField()),
            ],
            options={
                "db_table": "REFPRODUIT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "idCompagnie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="pharmamasque.compagnie",
                    ),
                ),
            ],
            options={
                "db_table": "LOCALISATION",
                "managed": False,
            },
        ),
    ]
